name: docker-build-and-push-release

on:
  release:
    types: [released, edited]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Get release version
        id: release_version
        uses: battila7/get-version-action@v2.2.1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: citygml4j/citygml-tools:${{ steps.release_version.outputs.version }},citygml4j/citygml-tools:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
